- description: 'Track code changes, undo mistakes, collaborate. This module is a must.'
  name: Version controlling with git
  repository: https://github.com/swcarpentry/git-novice
  status: stable
  videos: ''
  webpage: http://swcarpentry.github.io/git-novice
  id: git
- description: 'Working with branches and more.'
  name: Advanced git
  repository: https://github.com/hsf-training/hsf-training-advanced-git-webpage/
  status: alpha
  videos: ''
  webpage: ''
  id: advancedgit
- description: 'Get started with an incredibly popular programming language.'
  name: Programming with python
  repository: https://github.com/swcarpentry/python-novice-inflammation
  status: stable
  videos: ''
  webpage: http://swcarpentry.github.io/python-novice-inflammation
  id: python
- description: 'A full introduction to C++ based on a series of slides and exercises.'
  name: HEP C++ Course
  repository: https://github.com/hsf-training/cpluspluscourse
  status: stable
  videos: https://indico.cern.ch/event/979067/
  webpage: https://indico.cern.ch/event/979067/
  id: hepcpp
- description: 'A brand new C++ course that is currently in development.'
  name: Basic Modern C++
  repository: https://github.com/hsf-training/hsf-training-cpp-webpage
  status: alpha
  videos: ''
  webpage: https://hsf-training.github.io/hsf-training-cpp-webpage
  id: moderncpp
- description: 'Building code is hard. <code>CMake</code> makes it easier.'
  name: 'Build systems:  <code>cmake</code>'
  repository: https://github.com/hsf-training/hsf-training-cmake-webpage
  status: stable
  videos: ''
  webpage: https://hsf-training.github.io/hsf-training-cmake-webpage/
  id: cmake
- description: ''
  name: Distributed file systems and grid computing
  repository: ''
  status: alpha
  videos: ''
  webpage: ''
  id: grid
- description: 'The most famous data analysis framework used in HEP.'
  name: <code>ROOT</code>
  repository: ''
  status: alpha
  videos: ''
  webpage: ''
  id: root
- description: Reading and writing ROOT files without having to install ROOT.
  name: <code>uproot</code>
  repository: https://github.com/hsf-training/hsf-training-uproot-webpage
  status: beta
  videos: ''
  webpage: https://hsf-training.github.io/hsf-training-uproot-webpage/
  id: uproot
- description: A simple analysis using CMS open data.
  name: A simple analysis
  repository: https://github.com/hsf-training/hsf-training-cms-analysis-webpage
  status: stable
  videos: https://www.youtube.com/watch?v=gplMywJAFDI&list=PLKZ9c4ONm-Vk0wnDKaaovoEkOk3PVdL0V
  webpage: https://hsf-training.github.io/hsf-training-cms-analysis-webpage/
  id: simpleanalysis
- description: <a href="https://en.wikipedia.org/wiki/Unit_testing">Unit testing</a>
    in python.
  name: Unit testing
  repository: https://github.com/carpentries-incubator/python-testing
  status: beta
  videos: ''
  webpage: http://carpentries-incubator.github.io/python-testing/
  id: testingpython
- description: 'Make science prettier with beautiful plots!'
  name: Matplotlib for HEP
  repository: https://github.com/hsf-training/hsf-training-matplotlib
  status: beta
  videos: ''
  webpage: https://hsf-training.github.io/hsf-training-matplotlib/
  id: matplotlib
- description: ''
  name: Parallel programming
  repository: ''
  status: alpha
  videos: ''
  webpage: ''
  id: parallel
- description: Introduction to the <a href="https://www.docker.com/">docker</a> container
    image system.
  name: Docker
  repository: https://github.com/hsf-training/hsf-training-docker
  status: stable
  videos: https://www.youtube.com/watch?v=Qr42pEtio-Q&list=PLKZ9c4ONm-VnqD5oN2_8tXO0Yb1H_s0sj
  webpage: https://hsf-training.github.io/hsf-training-docker/index.html
  id: docker
- description: E.g. <code>yadage</code> and <code>reana</code>
  name: Workflows &amp; reproducibility
  repository: ''
  status: alpha
  videos: ''
  webpage: ''
  id: yadagereana
- description: 'Get behind the buzzword and teach machines to work for you intelligently!'
  name: Machine learning
  repository: https://github.com/hsf-training/hsf-training-ml-webpage
  status: stable
  videos: https://www.youtube.com/playlist?list=PLKZ9c4ONm-VmHsMKImIDEMsZI1Vp0UY-Z
  webpage: https://hsf-training.github.io/hsf-training-ml-webpage
  id: ml
- description: 'Speed up your machine learning using massive parallelization!'
  name: Machine learning on GPU
  repository: https://github.com/hsf-training/hsf-training-ml-gpu-webpage
  status: stable
  videos: https://www.youtube.com/playlist?list=PLKZ9c4ONm-VnfKk7XrVUa-V42lUdMrB6M
  webpage: https://hsf-training.github.io/hsf-training-ml-gpu-webpage
  id: gpuml
- description: <a href="https://docs.gitlab.com/ee/ci/">Continuous integration and
    deployment</a> with <a href="https://about.gitlab.com/">gitlab</a>.
  name: CI/CD (gitlab)
  repository: https://github.com/hsf-training/hsf-training-cicd
  status: stable
  videos: https://www.youtube.com/watch?v=C9auGFgIHns&list=PLKZ9c4ONm-VmmTObyNWpz4hB3Hgx8ZWSb
  webpage: https://hsf-training.github.io/hsf-training-cicd/
  id: cicd
- description: <a href="https://docs.gitlab.com/ee/ci/">Continuous integration and
    deployment</a> with <a href="https://github.com/features/actions">github actions</a>.
  name: CI/CD (github)
  repository: https://github.com/hsf-training/hsf-training-cicd-github
  status: stable
  videos: https://www.youtube.com/watch?v=-Xd5D6xKugk&list=PLKZ9c4ONm-Vl3kwsjrNRlPYNQFbPO2no4
  webpage: https://hsf-training.github.io/hsf-training-cicd-github/
  id: cicdgithub
- description: <code>sphinx</code>, <code>doxygen</code>, etc.
  name: Documentation
  repository: ''
  status: alpha
  videos: ''
  webpage: ''
  id: doc
- description: <code>pythia</code>, <code>sherpa</code>, <code>madgraph</code>, etc.
  name: Event generation and MC
  repository: ''
  status: alpha
  videos: ''
  webpage: ''
  id: generators
- description: <a href="https://alpaka.readthedocs.io/en/latest/index.html">alpaka</a>
    is a header-only C++ abstraction library for accelerator development.
  name: alpaka
  repository: https://github.com/hsf-training/hsf-training-alpaka-webpage
  status: alpha
  videos: ''
  webpage: ''
  id: alpaka
- description: Introduction to the <a href="https://en.wikipedia.org/wiki/Ssh_(Secure_Shell)">Secure Shell (SSH)</a>
  name: SSH
  repository: https://github.com/hsf-training/hsf-training-ssh-webpage/
  status: alpha
  videos: ''
  webpage: https://hsf-training.github.io/hsf-training-ssh-webpage/
  id: ssh
- description: A guide through the basics of the file systems and the shell.
  name: The UNIX Shell
  repository: https://github.com/swcarpentry/shell-novice
  status: stable
  videos: ''
  webpage: https://swcarpentry.github.io/shell-novice/
  id: unix
- description: A collection of packages for particle physics analyses in Python.
  name: Scikit-HEP
  status: beta
  videos: ''
  webpage: https://hsf-training.github.io/hsf-training-scikit-hep-webpage/
  id: scikithep
  repository: https://github.com/hsf-training/hsf-training-scikit-hep-webpage
- description: Introduction to containerization with <a href="https://apptainer.org/">Singularity/Apptainer</a>. 
  name: Singularity
  status: alpha
  videos: ''
  webpage: https://hsf-training.github.io/hsf-training-singularity-webpage/
  id: singularity
  repository: https://github.com/hsf-training/hsf-training-singularity-webpage





- description: 'Module introducing basics of software design.'
  name: Software Design
  repository: https://github.com/INTERSECT-training/Design
  status: alpha
  videos: ''
  webpage: https://intersect-training.org/Design/
  id: design

- description: 'Module introducing Python packaging and distribution.'
  name: Packaging
  repository: https://github.com/INTERSECT-training/packaging
  status: alpha
  videos: ''
  webpage: https://intersect-training.org/packaging/
  id: packaging

- description: 'Module introducing collaborative git.'
  name: Collaborative Git
  repository: https://github.com/INTERSECT-training/collaborative-git
  status: alpha
  videos: ''
  webpage: https://intersect-training.org/collaborative-git/
  id: collabgit

- description: 'Module introducing issue tracking.'
  name: Issue Tracking
  repository: https://github.com/INTERSECT-training/Issue-Tracking
  status: alpha
  videos: ''
  webpage: https://intersect-training.org/Issue-Tracking/
  id: issues

- description: 'Module introducing how to make good pull requests.'
  name: Making Good PRs
  repository: https://github.com/INTERSECT-training/Making-Good-PRs
  status: alpha
  videos: ''
  webpage: https://intersect-training.org/Making-Good-PRs/
  id: prs

- description: 'Module introducing software licensing.'
  name: Licensing 
  repository: https://github.com/INTERSECT-training/software-licensing
  status: alpha
  videos: ''
  webpage: https://intersect-training.org/software-licensing/
  id: licensing

- description: 'Module introducing code review.'
  name: Code Review
  repository: https://github.com/INTERSECT-training/Code-Review
  status: alpha
  videos: ''
  webpage: https://intersect-training.org/Code-Review/
  id: review

- description: 'Module introducing basics of building a community around a software package.'
  name: Building a Community
  repository: https://github.com/INTERSECT-training/Building-A-Community
  status: alpha
  videos: ''
  webpage: https://intersect-training.org/Building-A-Community/
  id: community

- description: 'Module introducing basics of systematic, automated testing.'
  name: Testing
  repository: https://github.com/INTERSECT-training/testing-lesson
  status: alpha
  videos: ''
  webpage: https://intersect-training.org/testing-lesson
  id: testing

- description: 'Module introducing continuous integration and continuous developement (CI/CD).'
  name: CI/CD
  repository: https://github.com/INTERSECT-training/CI-CD
  status: alpha
  videos: ''
  webpage: https://intersect-training.org/CI-CD/
  id: ci-cd

- description: 'Module introducing documentation practices.'
  name: Documentation
  repository: https://github.com/INTERSECT-training/Documentation
  status: alpha
  videos: ''
  webpage: https://intersect-training.org/Documentation/
  id: documentation

- description: 'Module introducing project management.'
  name: Project Management
  repository: https://github.com/INTERSECT-training/Project-Management
  status: alpha
  videos: ''
  webpage: https://intersect-training.org/Project-Management/
  id: project-management


  

